set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_CXX_COMPILER "cl")

if (NOT CMAKE_CXX_COMPILER)
    message(FATAL_ERROR "MSVC compiler (cl.exe) not found!")
endif()

set(CMAKE_CXX_FLAGS "/permissive- /GS /Zc:__cplusplus /Zc:alignedNew /Zc:char8_t ")
set(CMAKE_CXX_FLAGS_SOLARC_DEBUG "/Zi /Od /MDd")
set(CMAKE_CXX_FLAGS_SOLARC_RELEASE "/O2 /MD")
set(CMAKE_CXX_FLAGS_SOLARC_PROFILE "/O2 /Zi /MD")
set(CMAKE_CXX_FLAGS_SOLARC_TEST "/Zi /Od /MDd")

set(CMAKE_SHARED_LINKER_FLAGS "/OPT:REF /OPT:ICF /OPT:LBR /SUBSYSTEM:CONSOLE ")
set(CMAKE_EXE_LINKER_FLAGS "/OPT:REF /OPT:ICF /OPT:LBR /SUBSYSTEM:CONSOLE ")

set(CMAKE_SHARED_LINKER_FLAGS_SOLARC_RELEASE "/LTCG /SUBSYSTEM:WINDOWS /DEBUG:NONE")
set(CMAKE_EXE_LINKER_FLAGS_SOLARC_RELEASE    "/LTCG /SUBSYSTEM:WINDOWS /DEBUG:NONE")

set(CMAKE_SHARED_LINKER_FLAGS_SOLARC_DEBUG "/VERBOSE /DEBUG /INCREMENTAL /MAP")
set(CMAKE_EXE_LINKER_FLAGS_SOLARC_DEBUG    "/VERBOSE /DEBUG /INCREMENTAL /MAP")

set(CMAKE_SHARED_LINKER_FLAGS_SOLARC_PROFILE "/PROFILE")
set(CMAKE_EXE_LINKER_FLAGS_SOLARC_PROFILE "/PROFILE")

set(CMAKE_SHARED_LINKER_FLAGS_SOLARC_TEST "/DEBUG /INCREMENTAL /RTC1")
set(CMAKE_EXE_LINKER_FLAGS_SOLARC_TEST "/DEBUG /INCREMENTAL /RTC1")