set(CMAKE_SYSTEM_NAME Windows)

set(CMAKE_CXX_COMPILER g++)

if (NOT CMAKE_CXX_COMPILER)
    message(FATAL_ERROR "g++ compiler not found!")
endif()

include("./cmake/GCC_FLAGS.cmake")

set(CMAKE_SHARED_LINKER_FLAGS_R_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_R_RELEASE} -mwindows")
set(CMAKE_EXE_LINKER_FLAGS_R_RELEASE    "${CMAKE_SHARED_LINKER_FLAGS_R_RELEASE} -mwindows")