set(${MODULE_NAME}_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)
set(${MODULE_NAME}_INC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)

set(${MODULE_NAME}_SRC 
${${MODULE_NAME}_SRC_DIR}/main.cpp

)

set(${MODULE_NAME}_HDRS

)