set(${PROJECT_NAME}_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/src)
set(${PROJECT_NAME}_INC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/include)

set(${PROJECT_NAME}_SRC 
${${PROJECT_NAME}_SRC_DIR}/main.cpp

)

set(${PROJECT_NAME}_HDRS

)