get_property(is_multi_config GLOBAL PROPERTY GENERATOR_IS_MULTI_CONFIG)

if(is_multi_config)
	set(CMAKE_CONFIGURATION_TYPES "SOLARC_DEBUG;SOLARC_RELEASE;SOLARC_PROFILE;SOLARC_TEST" CACHE STRING "Types of configurations are/
	SOLARC_DEBUG , SOLARC_RELEASE , SOLARC_PROFILE and SOLARC_TEST ." FORCE)
else()
	if(NOT CMAKE_BUILD_TYPE)
		set(CMAKE_BUILD_TYPE "SOLARC_DEBUG" CACHE STRING "Default config type is SOLARC_DEBUG" FORCE)
	endif()
endif()

add_compile_definitions($<CONFIG>)
